name: Deploy to Hosting
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Hosting
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: server143.hosting.reg.ru
          username: u1894107_alex
          password: ${{ secrets.STAGING_FTP_PASSWORD }}
          server-dir:  /portamia.ru/wp-content/themes/mercato
